Task5
31Vladimir08/WebApplication pull request #12
Opened 2021-12-10 13:37 UTC by 31Vladimir08

Security

2021-12-17 14:53 UTC, Ungerfall commented
@31Vladimir08 , страницы Areas/Identity/ не нужны в проекте, если не делаешь кастомизацию, потому что они уже находятся в библиотках asp.net core

2021-12-17 15:03 UTC, Ungerfall commented on WebApplication/Program.cs
> +                    await RoleInitializer.InitializeAsync(userManager, rolesManager);
Data seeding лучше переделать согласно рекомендациям <https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding>

2021-12-17 15:10 UTC, Ungerfall requested changes
Нужно упростить. Ты добавил код, который уже есть в библиотеках asp.net core

2021-12-17 19:24 UTC, 31Vladimir08 commented on WebApplication/Program.cs
> +                    await RoleInitializer.InitializeAsync(userManager, rolesManager);
Исправил

2021-12-18 15:43 UTC, Ungerfall approved these changes
approved.

2021-12-18 15:43 UTC, merged